#21 add a script to setup tf alias

diff --git a/bin/generate_tfrc_credentials b/bin/generate_tfrc_credentials
--- a/bin/generate_tfrc_credentials
+++ b/bin/generate_tfrc_credentials
@@ -1,20 +1,29 @@
 #!/usr/bin/env bash
 
+# Define target directory and file
+TARGET_DIR="/home/gitpod/.terraform.d"
+TARGET_FILE="${TARGET_DIR}/credentials.tfrc.json"
+
 # Check if TERRAFORM_CLOUD_TOKEN is set
-#if [ -z "$TERRAFORM_CLOUD_TOKEN"]; THEN
-#    echo "ERROR: TERRAFORM_CLOUD_TOKEN environment variable is not set."
-#    exit 1
-#fi
+if [ -z "$TERRAFORM_CLOUD_TOKEN" ]; then
+    echo "Error: TERRAFORM_CLOUD_TOKEN environment variable is not set."
+    exit 1
+fi
+
+# Check if directory exists, if not, create it
+if [ ! -d "$TARGET_DIR" ]; then
+    mkdir -p "$TARGET_DIR"
+fi
 
 # Generate credentials.tfrc.json with the token
-cat > /home/gitpod/.terraform.d/credentials.tfrc.json << EOF
+cat > "$TARGET_FILE" << EOF
 {
-    "credentials": {
-        "app.terraform.io": {
-            "token": "$TERRAFORM_CLOUD_TOKEN"
-        }
+  "credentials": {
+    "app.terraform.io": {
+      "token": "$TERRAFORM_CLOUD_TOKEN"
     }
+  }
 }
 EOF
 
-echo "credentials.tfrc.json has been generated."
+echo "${TARGET_FILE} has been generated."
